services:
  - type: web
    name: sakina-shop-backend
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: SakinaShop
      - key: APP_ENV
        value: production
      - key: APP_BASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: sakina-shop
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FAL_KEY
        sync: false
